-- determines whether you want to use the small input (dayX_input_small.txt)
-- or the large, personalized input (dayX_input_large.txt) (REMEMBER TO PASTE YOUR OWN INPUT)
small_input = false

--dofile("day01.lua")
--dofile("day02.lua")
--dofile("day03.lua")
--dofile("day04.lua")
--dofile("day05.lua")
--dofile("day07.lua")
--dofile("day08.lua")
--dofile("day09.lua")
--dofile("day10.lua")
--dofile("day11.lua")
--dofile("day12.lua")
--dofile("day13.lua")
--dofile("day14.lua")
--dofile("day15.lua")
dofile("day16.lua")